version: ~> 1.0
language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed cinthialandia/udagram-api-feed:latest
  - docker tag udagram-api-user cinthialandia/udagram-api-user:latest
  - docker tag udagram-frontend cinthialandia/udagram-frontend:latest
  - docker tag reverseproxy cinthialandia/reverseproxy:latest

after_success:
  # Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push cinthialandia/udagram-api-feed:latest
  - docker push cinthialandia/udagram-api-user:latest
  - docker push cinthialandia/udagram-frontend:latest
  - docker push cinthialandia/reverseproxy:latest

